[build]
  publish = "frontend/dist"
  command = "npm --prefix frontend run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*.{js,css}"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"